name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # every day at 03:00 UTC
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  update-readme:
    name: WakaTime dev metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          TIME_RANGE: last_7_days
          LANG_COUNT: 6
          PROGRESS_SYMBOL_VERSION: 2
          COMMIT_MESSAGE: "chore(readme): update WakaTime stats"
